before_script:
  - cd Fit
  - echo 'sdk.dir='$ANDROID_HOME > local.properties

stages:
  - build
  - test
  - deploy

build_project:
  stage: build
  only:
    - develop
  script:
    - fastlane build
  tags:
    - android

deploy_project:
  stage: build
  only:
    - master
  script:
    - fastlane build
  tags:
    - android
