#update_fastlane

default_platform :android

platform :android do

  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build the Project Only"
  lane :build do
    gradle(task: "clean")
    gradle(task: "assemble", build_type: "Release")
  end

  desc "Submit a new Alpha Build"
  lane :alpha do
    gradle(task: "clean")
    gradle(task: "assemble", build_type: "Release")
    supply(track: "alpha")
  end

  desc "Submit a new Beta Build"
  lane :beta do
    gradle(task: "clean")
    gradle(task: "assemble", build_type: "Release")
    supply(track: "beta")
  end



  after_all do |lane|
    # This block is called, only if the executed lane was successful
  end

  error do |lane, exception|
    # slack
  end

end